// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP2zBpcQy2cZR3-zW1ppLzawLAFEcBfec',
    appId: '1:1012520686586:web:c6bdb7537972598ac80a43',
    messagingSenderId: '1012520686586',
    projectId: 'pomodoro-53754',
    authDomain: 'pomodoro-53754.firebaseapp.com',
    storageBucket: 'pomodoro-53754.firebasestorage.app',
    measurementId: 'G-B24FKM33JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyJBR26PKblOdauVOjamHztwX_KtoUBM',
    appId: '1:1012520686586:android:40ebaebd3bec21a0c80a43',
    messagingSenderId: '1012520686586',
    projectId: 'pomodoro-53754',
    storageBucket: 'pomodoro-53754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbSYtsTZoFGG_B1v5NHyYNUZqOhM3_Js',
    appId: '1:1012520686586:ios:4d66003a2ad3890bc80a43',
    messagingSenderId: '1012520686586',
    projectId: 'pomodoro-53754',
    storageBucket: 'pomodoro-53754.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbSYtsTZoFGG_B1v5NHyYNUZqOhM3_Js',
    appId: '1:1012520686586:ios:4d66003a2ad3890bc80a43',
    messagingSenderId: '1012520686586',
    projectId: 'pomodoro-53754',
    storageBucket: 'pomodoro-53754.firebasestorage.app',
    iosBundleId: 'com.example.pomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP2zBpcQy2cZR3-zW1ppLzawLAFEcBfec',
    appId: '1:1012520686586:web:8fe62c8e79771b0ec80a43',
    messagingSenderId: '1012520686586',
    projectId: 'pomodoro-53754',
    authDomain: 'pomodoro-53754.firebaseapp.com',
    storageBucket: 'pomodoro-53754.firebasestorage.app',
    measurementId: 'G-6CRC6C2EVW',
  );
}
